Documents/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import upload_document, document_list, page
from . import views

app_name = 'documents'

urlpatterns = [
                  # path('', home, name='home'), # Home page
                  path('upload/', views.upload_document, name='upload_document'),
                  path('documents/', views.document_list, name='document_list'),
                  #path('document_list/', views.document_list, name='document_list'),
                  path('documents/delete/<int:document_id>/', views.document_delete, name='document_delete'),
                  path('', page, name='page'),  # page/

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InvMngSys/urls.py
from django.conf import settings
from django.conf.urls.static import static

from dashboard.views import dashboard_view
from . import views
from InvMngSys.custom_admin import custom_admin_site
from django.contrib.auth import views as auth_views
from django.urls import path, include
from .views import password_reset_confirm_custom

urlpatterns = [
                  path('', views.homepage, name='homepage'),
                  #path('', dashboard_view, name='dashboard_redirect'),  # Redirect from root to dashboard
                  path('admin/', custom_admin_site.urls),
                  path('inventory/', include('Inventory.urls', namespace='inventory')),  # items/
                  path('documents/', include('Documents.urls', namespace='documents')),  # documents/
                  path('financials/', include('financials.urls', namespace='financials')),  # financials/
                  path('cashier/', include('cashier.urls', namespace='cashier')),  # cashier/
                  path('login/', auth_views.LoginView.as_view(), name='login'),
                  path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
                  path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
                  path('reset/<uidb64>/<token>/', password_reset_confirm_custom, name='password_reset_confirm'),
                  # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
                  path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
                  path('invalid-link/', views.invalid_link, name='invalid_link'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Inventory/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'Inventory'

urlpatterns=[
	path('inventory/', views.item_list, name='item_list'),
	path('inventory/<int:item_id>/', views.item_details, name='item_details'),
	path('<int:item_id>/transfer', views.transferitm, name='transferitm'),
	path('<int:item_id>/return', views.returnitm, name='returnitm'),
	path('rebuy-list/', views.rebuy_list, name='rebuy_list'),
	path('item/edit/<int:item_id>/', views.item_edit, name='item_edit'),
	path('item/delete/<int:item_id>/', views.item_delete, name='item_delete'),
	path('item/create/', views.item_create, name='item_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cashier/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import update_results

app_name = 'cashier'

urlpatterns = [
                  path('cashier/', views.cashier, name='cashier'),
                  path('search/', views.search_item, name='search_item'),
                  path('clear_results/', views.clear_results, name='clear_results'),
                  path('create_transactions/', views.create_transactions, name='create_transactions'),
                  path('wholesale/', views.wholesale, name='wholesale'),
                  path('wholesale_create_transactions/', views.wholesale_create_transactions,
                       name='wholesale_create_transactions'),
                  path('wholesale_search/', views.wholesale_search_item, name='wholesale_search_item'),
                  path('cashier/search/update_results/', update_results, name='update_results'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

financials/urls.py
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from . import views

app_name = 'financials'

from django.urls import path
from . import views


app_name = 'financials'


urlpatterns = [
    path('financials/', views.financials, name='financials'),
    path('financials/transaction_list/', views.transaction_list, name='transaction_list'),
    path('financials/balance_sheet/', views.balance_sheet, name='balance_sheet'),

    # path('transactions/<int:transaction_id>/', views.transaction_details, name='transaction_details'),
    # path('balance/', views.balance, name='balance'),
    # path('income_statement/', views.income_statement, name='income_statement'),
    # Invoices
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InvMngSys/views.py
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.utils.http import base36_to_int
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.models import User
from django.utils.http import int_to_base36
import logging

logger = logging.getLogger(__name__)


@login_required
def homepage(request):
    return render(request, 'homepage.html')


def invalid_link(request):
    return render(request, 'invalid_link.html')


def password_reset_confirm_custom(request, uidb64, token):
    try:
        uid = base36_to_int(uidb64)
        logger.warning(f"Decoded uidb64: {uidb64}, Decoded uid: {uid}")
        user = User.objects.get(pk=uid)

    except (ValueError, OverflowError, User.DoesNotExist) as e:
        logger.error(f"Error in password_reset_confirm_custom: {e}")
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        # The uidb64 and token are valid, show the password reset form
        return PasswordResetConfirmView.as_view()(request, uidb64=uidb64, token=token)
    else:
        # Invalid uidb64 or token, redirect to an error page or handle as needed
        ouss = get_user_model().objects.get(username='Oussama')
        logger.warning(f"Invalid uidb64 or token - uid: {uid}, token: {token},  user: {user}, Ouss: {ouss.id}")
        return HttpResponseRedirect('/invalid-link/')  # You can customize the redirect URL

InvMngSys/templates/homepage.html
{% load static %}
<html>
<head>
    <title>ITEMS</title>
    <script type="text/javascript" src="{% static 'jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="{% static 'DataTables/datatables.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'DataTables/datatables.css' %}" />
    <script type="text/javascript" charset="utf8" src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="icon" href="{% static 'logo2.ico' %}">
    <style>
        body {
            background-image: url('{% get_media_prefix %}images/homepage_background.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center center;
            color: white; /* Set text color to white */
        }
        .btn-primary:hover {
            background-color: #5cb85c; /* Change button color on hover */
        }
    </style>
</head>
<body>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <div class="jumbotron text-center">
        <h1 class="display-3">Welcome to the Inventory Management System!</h1>
        <p class="lead">This is the homepage, where you can access the different parts of the system.</p>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h2 class="card-title">Cashier</h2>
                        <p class="card-text">Scan items and create transactions.</p>
                        <a href="{% url 'cashier:cashier' %}" class="btn btn-primary">Go to Cashier</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h2 class="card-title">Inventory</h2>
                        <p class="card-text">View and manage inventory items.</p>
                        <a href="{% url 'inventory:item_list' %}" class="btn btn-primary">Go to Inventory</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h2 class="card-title">Wholesale</h2>
                        <p class="card-text">Create bulk purchase deals.</p>
                        <a href="{% url 'cashier:wholesale' %}" class="btn btn-primary">Go to Wholesale</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h2 class="card-title">Financials</h2>
                        <p class="card-text">View and manage financial transactions.</p>
                        <a href="{% url 'financials:financials' %}" class="btn btn-primary">Go to Financials</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h2 class="card-title">Documents</h2>
                        <p class="card-text">Upload and manage documents.</p>
                        <a href="{% url 'documents:page' %}" class="btn btn-primary">Go to Documents</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h2 class="card-title">Administration</h2>
                        <p class="card-text">Access the admin panel.</p>
                        <a href="{% url 'admin:index' %}" class="btn btn-primary">Go to Admin Panel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

InvMngSys/templates/invalid_link.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invalid Link</title>
</head>
<body>
    <div style="text-align: center; margin-top: 50px;">
        <h1>Invalid Link</h1>
        <p>The password reset link is invalid or has expired. Please request a new password reset link.</p>
        <a href="{% url 'password_reset' %}">Request Password Reset</a>
    </div>
</body>
</html>