InvMngSys/urls.py
from django.conf import settings
from django.conf.urls.static import static

from dashboard.views import dashboard_view
from . import views
from InvMngSys.custom_admin import custom_admin_site
from django.contrib.auth import views as auth_views
from django.urls import path, include
from .views import password_reset_confirm_custom

urlpatterns = [
                  path('', views.homepage, name='homepage'),
                  #path('', dashboard_view, name='dashboard_redirect'),  # Redirect from root to dashboard
                  path('admin/', custom_admin_site.urls),
                  path('inventory/', include('Inventory.urls', namespace='inventory')),  # items/
                  path('documents/', include('Documents.urls', namespace='documents')),  # documents/
                  path('financials/', include('financials.urls', namespace='financials')),  # financials/
                  path('cashier/', include('cashier.urls', namespace='cashier')),  # cashier/
                  path('login/', auth_views.LoginView.as_view(), name='login'),
                  path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
                  path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
                  path('reset/<uidb64>/<token>/', password_reset_confirm_custom, name='password_reset_confirm'),
                  # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
                  path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
                  path('invalid-link/', views.invalid_link, name='invalid_link'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Inventory/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'Inventory'

urlpatterns=[
	path('inventory/', views.item_list, name='item_list'),
	path('inventory/<int:item_id>/', views.item_details, name='item_details'),
	path('<int:item_id>/transfer', views.transferitm, name='transferitm'),
	path('<int:item_id>/return', views.returnitm, name='returnitm'),
	path('rebuy-list/', views.rebuy_list, name='rebuy_list'),
	path('item/edit/<int:item_id>/', views.item_edit, name='item_edit'),
	path('item/delete/<int:item_id>/', views.item_delete, name='item_delete'),
	path('item/create/', views.item_create, name='item_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cashier/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import update_results

app_name = 'cashier'

urlpatterns = [
                  path('cashier/', views.cashier, name='cashier'),
                  path('search/', views.search_item, name='search_item'),
                  path('clear_results/', views.clear_results, name='clear_results'),
                  path('create_transactions/', views.create_transactions, name='create_transactions'),
                  path('wholesale/', views.wholesale, name='wholesale'),
                  path('wholesale_create_transactions/', views.wholesale_create_transactions,
                       name='wholesale_create_transactions'),
                  path('wholesale_search/', views.wholesale_search_item, name='wholesale_search_item'),
                  path('cashier/search/update_results/', update_results, name='update_results'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Inventory/models.py
from django.db import models
from datetime import datetime, timedelta


# Create your models here.

class Category(models.Model):
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.category


class Item(models.Model):
    item_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    company = models.CharField(max_length=120, blank=True, null=True)
    description = models.CharField(max_length=250, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.IntegerField(default=0)
    rebuy_till = models.IntegerField(default=0)
    purchase_cost = models.FloatField(default=0)
    shipping_cost = models.FloatField(default=0)
    selling_price = models.FloatField(default=0)
    TVA = models.FloatField(default=0)
    code = models.CharField(max_length=256, blank=True, null=True)


    def __str__(self):
        return self.name


class Client(models.Model):
    name = models.CharField(max_length=80)
    place = models.CharField(max_length=50)
    description = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Transaction(models.Model):
    trans_id = models.AutoField(primary_key=True)
    quantity = models.IntegerField()
    selling_price = models.FloatField()
    time = models.DateTimeField(blank=True, null=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, blank=False, null=False)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    user =  models.CharField(max_length=100,blank=True, null=True,editable=False)
    discount = models.FloatField(default=0)
    type= models.CharField(max_length=100,editable=False)
    profit = models.FloatField()
    TVA = models.FloatField(default=0)

    def save(self, *args, **kwargs):
        # Get the current datetime
        current_datetime = datetime.now()

        # Format the datetime as a string
        formatted_datetime = current_datetime.strftime('%Y-%m-%d %H:%M:%S')

        # Set the formatted datetime as the value for the field
        self.time = formatted_datetime

        super().save(*args, **kwargs)

    def __str__(self):
        if self.client is not None:
            return ("%s , %s , %s, %s, %s" % (self.item.name, self.client.place, self.time, self.user, self.type))
        else:
            return ("%s , %s, %s, %s" % (self.item.name, self.time, self.user, self.type))

Inventory/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'company', 'category', 'quantity', 'purchase_cost', 'shipping_cost', 'selling_price', 'description','rebuy_till','code']

Inventory/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import Item, Transaction, Client
from django.shortcuts import render, get_object_or_404
from django import forms
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import Item
from .forms import ItemForm
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages

from .models import Item
from .forms import ItemForm


def item_list(request):
    items = Item.objects.all().order_by('-item_id')
    return render(request, 'item_list.html', {'items': items})


def item_create(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            item = form.save()
            return redirect('Inventory:item_list')
    else:
        form = ItemForm()
    return render(request, 'item_create.html', {'form': form})


def item_edit(request, item_id):
    item = get_object_or_404(Item, item_id=item_id)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('Inventory:item_list')
    else:
        form = ItemForm(instance=item)
    return render(request, 'item_edit.html', {'form': form})


def item_delete(request, item_id):
    item = get_object_or_404(Item, item_id=item_id)
    if request.method == 'POST':
        item.delete()
        return redirect('Inventory:item_list')
    return render(request, 'Inventory/item_delete.html', {'item': item})


def rebuy_list(request):
    items = Item.objects.all()
    return render(request, 'rebuy_list.html', {'items': items})


def item_details(request, item_id):
    discount = 0
    type = "NULL"
    item = get_object_or_404(Item, pk=item_id)
    clients = Client.objects.all()
    context = {'item': item, 'clients': clients}
    if request.method == 'POST':
        quantity = request.POST['quantity']
        client = request.POST['client']
        selling_price = request.POST['selling_price']  # get the selling_price value from POST request
        if 'transfer' in request.POST:
            transaction_type = Transaction.TYPE_CHOICES[0][0]
            type = 'transfer'
            item.quantity -= int(quantity)
            item.save()
            discount = item.selling_price - request.POST['selling_price']
        elif 'return' in request.POST:
            transaction_type = Transaction.TYPE_CHOICES[1][0]
            type = 'return'
            item.quantity += int(quantity)
            item.save()
            discount = request.POST['selling_price'] - item.selling_price
        transaction = Transaction.objects.create(
            item=item,
            client=client,
            quantity=int(quantity),
            transaction_type=transaction_type,
            selling_price=float(selling_price) * int(quantity),  # save the selling_price value in the Transaction model
            discount=discount * int(quantity),
            type=type,
            TVA=round(float(selling_price) * 0.11 * int(quantity), 2)
        )
        transaction.save()
        return redirect('item_details', context)
    return render(request, 'details.html', context)


def transferitm(request, item_id):
    client = Client.objects.get(name=request.POST.get("client"))
    type = 'transfer'
    item = Item.objects.get(pk=item_id)
    quantity = request.POST.get("quantity")
    # selling_price = request.POST.get("selling_price")
    selling_price = request.POST.get("selling_price")
    user = request.user.username
    discount = ((item.selling_price) - float(request.POST['selling_price'])) * int(quantity)
    profit = ((item.selling_price - item.purchase_cost - item.shipping_cost) * int(quantity)) - discount
    TVA = round(float(request.POST['selling_price']) * 0.11 * int(quantity), 2)
    transaction = Transaction(quantity=quantity, item=item, client=client, selling_price=selling_price, user=user,
                              discount=discount, type=type, profit=profit, TVA=TVA)
    transaction.save()
    item.quantity = item.quantity - int(quantity)
    item.save()
    return render(request, 'transferitm.html',
                  {'transaction': transaction, 'quantity': quantity, 'item': item, 'Selling Price': selling_price,
                   user: 'User', client: 'client', TVA: 'TVA'})


def returnitm(request, item_id):
    client = Client.objects.get(name=request.POST.get("client"))
    type = 'return'
    item = Item.objects.get(pk=item_id)
    quantity = request.POST.get("quantity")
    selling_price = request.POST.get("selling_price")
    user = request.user.username
    discount = (float(request.POST['selling_price']) - item.selling_price) * int(quantity)
    profit = ((item.shipping_cost + item.purchase_cost - item.selling_price) * int(quantity)) - discount

    transaction = Transaction(quantity=quantity, item=item, client=client, selling_price=selling_price, user=user,
                              discount=discount, type=type, profit=profit)
    transaction.save()
    item.quantity = item.quantity + int(quantity)
    item.save()
    return render(request, 'returnitm.html',
                  {'transaction': transaction, 'quantity': quantity, 'item': item, 'Selling Price': selling_price,
                   user: 'User', client: 'client'})

Inventory/templates/base.html
{% load static %}
<html>
<head>
    <title>ITEMS</title>
    <script type="text/javascript" src="{% static 'jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="{% static 'DataTables/datatables.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'DataTables/datatables.css' %}"/>
    <script type="text/javascript" charset="utf8" src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="icon" href="{% static 'logo2.ico' %}">
    <style>
        body {
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center center;
            color: white; /* Set text color to white */
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); /* Text shadow for readability */
            position: relative;

        }
        body::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5); /* Overlay for better contrast */
            z-index: -1;
        }
        .btn-primary:hover {
            background-color: #5cb85c; /* Change button color on hover */
        }
    </style>
</head>
<body>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block content %}
{% endblock %}
<center><a class="btn btn-primary" href="/">HOME</a></center>
</body>
</html>

Inventory/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    body {
        background-image: url('{% get_media_prefix %}/images/inventory_background.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center center;
        color: white; /* Set text color to white */
        margin: 0;
        padding: 150px;
    }
    .card {
        margin-top: 500px; /* Pushing the card down by 200px */
        width: 50rem;
        background-color: #333; /* Card background color */
        color: white; /* Card text color */
        border-radius: 15px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        margin: 0 auto; /* Centering the card horizontally */
    }
    .card-header {
        background-color: #007bff; /* Header background color */
        color: white; /* Header text color */
        padding: 15px;
        font-weight: bold;
        border-top-left-radius: 15px;
        border-top-right-radius: 15px;
    }
    .card-body {
        padding: 20px;
    }
    label {
        color: white; /* Label text color */
    }
    input[type="number"],
    input[type="text"],
    select {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        background-color: #555; /* Input background color */
        color: white; /* Input text color */
    }
    input[type="submit"] {
        width: 100%;
        padding: 12px;
        border: none;
        border-radius: 4px;
        background-color: #007bff; /* Submit button background color */
        color: white; /* Submit button text color */
        cursor: pointer;
        transition: background-color 0.3s ease;
    }
    input[type="submit"]:hover {
        background-color: #0056b3; /* Hover background color */
    }
    .btn-secondary {
        padding: 12px;
        border: none;
        border-radius: 4px;
        background-color: #6c757d; /* Secondary button background color */
        color: white; /* Secondary button text color */
        cursor: pointer;
        transition: background-color 0.3s ease;
        margin-top: 20px;
    }
    .btn-secondary:hover {
        background-color: #495057; /* Hover background color for secondary button */
    }
</style>


<div class="card">
    <div class="card-header">RETURN {{ item.name }}</div>
    <div class="card-body">
        <form action="{% url 'inventory:returnitm' item.item_id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="item" value="{{ item.name }}">
            <div class="form-group">
                <label for="quantity">Quantity</label>
                <input type="number" class="form-control" value="1" id="quantity" name="quantity" min="1" required/>
            </div>
            <div class="form-group">
                <label for="client">Client</label>
                <select name="client" class="form-control" id="client">
                    {% for client in clients %}
                        <option value="{{ client.name }}">{{ client.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="price">Selling Price</label>
                <input type="text" class="form-control" id="selling_price" name="selling_price" value="{{ item.selling_price }}" required/>
            </div>
            <input type="submit" class="btn btn-primary" value="RETURN">
        </form>
    </div>
</div>

<button onclick="goBack()" class="btn btn-secondary">Back</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>

{% endblock %}

Inventory/templates/document_deleted.html
{% extends 'base.html' %}

{% block content %}
    <h2>Document Deleted</h2>
    <p>The document "{{ document.title }}" has been deleted.</p>
{% endblock %}

Inventory/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <h2>Inventory Management System</h2>
  {% if items %}
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Category</th>
          <th>Quantity</th>
          <th>Purchase Cost</th>
          <th>Shipping Cost</th>
          <th>Selling Price</th>
          <th>Code</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
          <tr>
            <td>{{ item.item_id }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.category }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.purchase_cost }}</td>
            <td>{{ item.shipping_cost }}</td>
            <td>{{ item.selling_price }}</td>
            <td>{{ item.code }}</td>
            <td>
              <a href="{% url 'Inventory:item_details' item_id=item.item_id %}" class="btn btn-primary">Details</a>
              <a href="{% url 'Inventory:transferitm' item_id=item.item_id %}" class="btn btn-success">Transfer</a>
              <a href="{% url 'Inventory:returnitm' item_id=item.item_id %}" class="btn btn-warning">Return</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No items in inventory.</p>
  {% endif %}
  <a href="{% url 'Inventory:item_create' %}" class="btn btn-info">Add Item</a>
{% endblock %}

Inventory/templates/item_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    body {
        background-image: url('{% get_media_prefix %}/images/inventory_background.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center center;
        color: white; /* Set text color to white */
        font-family: Arial, sans-serif; /* Use a specific font for better readability */
    }
    .form-wrapper {
        padding-top: 10; /* Remove previous padding */
        margin-top: -50px; /* Lift the content up by 50 pixels */
        position: relative;
    }
    .form-field {
        margin-bottom: 10px;
    }
    .form-label {
        font-weight: bold;
        margin-bottom: 8px;
        display: block;
        font-size: 16px;
    }
    .form-control {
        width: calc(100% - 10px); /* Adjust the input width */
        padding: 10px;
        font-size: 16px;
        border-radius: 6px;
        border: 1px solid #ccc;
        background-color: #f8f8f8;
        transition: border-color 0.3s;
    }
    .form-control:focus {
        outline: none;
        border-color: #5cb85c; /* Highlight the input on focus */
    }
    .btn-primary {
        margin-top: 20px;
        padding: 10px 20px;
        font-size: 16px;
        border-radius: 6px;
        transition: background-color 0.3s;
    }
    .btn-primary:hover {
        background-color: #5cb85c; /* Change button color on hover */
    }
</style>

<div class="container form-wrapper">
    <h1 class="text-center mt-5 mb-4">Create Item</h1>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% for field in form %}
                    <div class="form-field">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>
    <button onclick="goBack()" class="btn btn-secondary mt-3">Back</button>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

{% endblock %}

Inventory/templates/item_edit.html
<!-- item_edit.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    body {
        background-image: url('{% get_media_prefix %}/images/inventory_background.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center center;
        color: white; /* Set text color to white */
        font-family: Arial, sans-serif; /* Use a specific font for better readability */
        padding: 10px;
    }
    .form-wrapper {
        padding-top: 10; /* Remove previous padding */
        margin-top: -60px; /* Adjust the margin top */
        color: white;
    }
    .form-field {
        margin-bottom: 10px;
    }
    .form-label {
        font-weight: bold;
        margin-bottom: 8px;
        display: block;
        font-size: 16px;
    }
    .form-control {
        width: calc(100% - 10px);
        padding: 10px;
        font-size: 16px;
        border-radius: 6px;
        border: 1px solid #ccc;
        background-color: #f8f8f8;
        transition: border-color 0.3s;
    }
    .form-control:focus {
        outline: none;
        border-color: #5cb85c;
    }
    .btn-primary {
        margin-top: 20px;
        padding: 10px 20px;
        font-size: 16px;
        border-radius: 6px;
        transition: background-color 0.3s;
    }
    .btn-primary:hover {
        background-color: #5cb85c;
    }
</style>

<div class="container form-wrapper">
    <h1 class="text-center mt-5 mb-4">Edit Item</h1>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% for field in form %}
                    <div class="form-field">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>
    <button onclick="goBack()" class="btn btn-secondary mt-3">Back</button>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

{% endblock %}

Inventory/templates/item_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    body {
        background-image: url('{% get_media_prefix %}/images/inventory_background.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center center;
        color: white; /* Set text color to white */
    }

    h1 {
        color: white; /* Set text color of h1 to white */
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        padding: 10px;
        text-align: left;
        border-bottom: 1px solid #ccc;
        color: white; /* Set text color of table cells to white */
        /*font-weight: bold; */ /* Set text to bold */
    }

    th {
        background-color: #343a40; /* Header row background color */
    }
</style>
<div class="d-flex justify-content-between align-items-center mb-3">
  <h1 class="text-center mb-5">All Items</h1>
  <div>
    <a href="{% url 'Inventory:rebuy_list' %}" class="btn btn-primary mr-2">Rebuy List</a>
    <a href="{% url 'Inventory:item_create' %}" class="btn btn-primary">Create</a>
  </div>
</div>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-dark">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Company</th>
        <th>Category</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Description</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
      <tr>
        <td>{{ item.name }}</td>
        <td>{{ item.company }}</td>
        <td>{{ item.category }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.selling_price }}</td>
        <td>{{ item.description }}</td>
        <td>
          <a href="{% url 'Inventory:item_details' item.item_id %}" class="btn btn-primary btn-sm mr-2">Return</a>
          <a href="{% url 'Inventory:item_edit' item.item_id %}" class="btn btn-primary btn-sm mr-2">Edit</a>
          <form action="{% url 'Inventory:item_delete' item.item_id %}" method="post" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this item?')">Delete</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock %}

Inventory/templates/rebuy_list.html
{% extends 'base.html' %}
{% load static %}
{% load inventory_filters %}
{% load mathfilters %}

{% block content %}
<style>
    body {
        background-image: url('{% get_media_prefix %}/images/inventory_background.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center center;
        color: white; /* Set text color to white */
    }
</style>
  <div class="jumbotron text-center">
    <h1>Rebuy List</h1>
    <p>Items that need to be rebought.</p>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <table class="table table-dark table-striped">
          <thead>
            <tr>
              <th>Item</th>
              <th>Current Quantity</th>
              <th>Rebuy Till Quantity</th>
              <th>Quantity to Rebuy</th>
            </tr>
          </thead>
          <tbody>
            {% for item in items %}
              {% if item.quantity < item.rebuy_till %}
                <tr>
                  <td>{{ item.name }}</td>
                  <td>{{ item.quantity }}</td>
                  <td>{{ item.rebuy_till }}</td>
                  <td>{{ item.rebuy_till|sub:item.quantity }}</td>
                </tr>
              {% endif %}
            {% empty %}
              <tr>
                <td colspan="4">No items need to be rebought.</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
<button onclick="goBack()" class="btn btn-secondary">Back</button>

<script>
function goBack() {
  window.history.back();
}
</script>

{% endblock %}

<style>
  th {
    font-weight: bold;
    text-align: center;
  }

  td {
    text-align: center;
  }
</style>

Inventory/templates/returnitm.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    body {
        background-image: url('{% get_media_prefix %}/images/inventory_background.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center center;
        color: white; /* Set text color to white */
    }
</style>
<div class="alert alert-primary" role="alert">
<h1>TRANSACTION : {{ transaction.trans_id }}<h1> Return {{ quantity }} {{ item.name }} was succesful!
<div>
{% endblock %}

Inventory/templates/transferitm.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-primary" role="alert">
<h1>TRANSACTION : {{ transaction.trans_id }}<h1>  Transfer {{ quantity }} {{ item.name }}s by {{ user }} was succesful!
<div>
{% endblock %}